### PR TITLE
Document the .Modal component

### PR DESCRIPTION
**Pull request by paddyduke**

### CODE REVIEW

**Comment by paddyduke** [comment]
@summers1981FA @atikamary I should have been clearer that this documentation very deliberately avoids any specific guidance on types of modal we have yet to try building with this component. Workflow and feature modals have been explicitly excluded from the content guidelines until we've designed and built them, and thus discovered what those guidelines should be.

The key benefit of components and documentation is they make it easier to repeat our successes. So we shouldn't have too many speculative rules for things we haven't done yet.

**Comment by craigcwaveformlabs** [comment]
@paddyduke as per today's tactical meeting, looking to merge this into master if it's ready to have a look over?

**Comment by paddyduke** [comment]
@craigcwaveformlabs Yep, if you could have a quick look that'd be great.

**Comment by craigcwaveformlabs** [comment]
@paddyduke Looks good to me 👍

**Pull request merged**
