### PR TITLE
Asset gem WIP

### PR DESCRIPTION
**Pull request by murraysum**
Prototype packaging origin as a ruby gem. For rails apps such as the desktop app we can use rails engines to include the assets. I have still to include an example of implementing it in a rails app.

Examples of importing origin as an asset gem using Sprockets :

https://github.com/fac/website/pull/956
https://github.com/fac/freeagent/pull/8457
https://github.com/fac/campaigner/pull/75
https://github.com/fac/fieldagent/pull/694

Potentially fapd-portal and data-warehouse in the future.

TODOS

* [x] Bring PR up to date.
* [x] Bring other PRs up to date.
  - [x] FreeAgent
  - [x] Website
  - [x] Campaigner
  - [x] FieldAgent
* [x] How does building out the origin docs work with the asset gem?
* [x] Does bringing in origin as an asset gem match up with designers workflow? Probably some pairing required to understand.
* [x] Run the implementations past the engineering team at the engineering forum and ask for comments/concerns

### CODE REVIEW

**Comment by robbiemanson** [comment]
Nice work!

I'm wondering whether we adopt the Gem as the defacto way of managing and implementing Origin, and ditch npm altogether. npm makes it really easy for designers to publish new versions, and has enough in the way of user/contributor permissions for us. How would switching to rubygems change any of that?

Where would the stylesheets installed by the gem actually live? What paths would we use to reference them from inside the local stylesheets (e.g. in `app/assets/stylesheets`)?

What would the process be for updating to a new version of the Gem?

**Comment by murraysum** [comment]
> I'm wondering whether we adopt the Gem as the defacto way of managing and implementing Origin, and ditch npm altogether. npm makes it really easy for designers to publish new versions, and has enough in the way of user/contributor permissions for us. How would switching to rubygems change any of that?

@robbiemanson There isn't anything to say we couldn't have npm and gem implementations. However, as you say if npm isn't really adding anything at the moment then we could look at adopting the Gem approach as the defacto way. There should be any real major changes to the publishing cycle compared to npm. There are two ways to publish a gem. Either you can publish to rubygems itself or you can pull the gem in from the github repo. 

*Ruby Gems publishing*
For the former you would just bump `https://github.com/fac/origin/blob/asset-gem/lib/origin/version.rb` and then tag the release in github. Then you'd build and publish the gem. See here for details (http://guides.rubygems.org/publishing/). Then in your gem file for the project you want to install it would just be updating the version number and then doing `bundle install`

```
gem "origin", "0.3.16"
```

*Pull from Git repo*
For the latter approach you would just bump https://github.com/fac/origin/blob/asset-gem/lib/origin/version.rb and then tag the release in github. Then in your gem file for the project you want to install it would just be updating the version number and then doing `bundle install`:

```
gem "origin", "0.3.16",  :github => "git@github.com:fac/origin.git"
```

> Where would the stylesheets installed by the gem actually live?

These would be internally added to the Sprockets path for the application. So they wouldn't be committed to the projects repo like the desktop app does at the moment. Simply you could have the path as what ever you really wanted really. For example to `@import` a stylesheet to use then it could be: `@import "origin/global/fonts/_font-functions";` Nice, simple and clean IMO

> What would the process be for updating to a new version of the Gem?

Sort of elaborated above how the publishing system works. See above.

I'll prototype a branch that switches over the desktop app to show you how it could look.

**Comment by ball-hayden** [comment]
[Origin Gem](https://trello.com/c/STibPgtE/1391-origin-gem)

**Comment by railsbob** [comment]
I've checked this branch against `fieldagent` and I don't see any issues :100:

**Comment by paddyduke** [comment]
@ball-hayden The updated docs/instructions look great. It's still missing anything about using the local version of the gem in the dev environment, but I don't really think that should hold up shipping the gem.

**Pull request merged**
