### PR TITLE
Add google analytics tracking code

### PR DESCRIPTION
**Pull request by stugoo**
To inform on how we can make improvements to FreeStyle, I've added some tracking code to determine how often and what sections of FreeStyle are in use.

### CODE REVIEW

**Comment by summers1981FA** [comment]
Hey,

The code looks fine to me but should we place this immediately inside the head? Is it still the case the higher up in the page the code the better?

**Comment by stugoo** [comment]
The docs say 
> immediately after the <head> tag on every page of your site 

https://developers.google.com/analytics/devguides/collection/gtagjs/

So I assumed it was the first thing inside the `body` element, as it's invalid to have anything out-with the head/body

**Comment by stugoo** [comment]
My mistake, the admin dashboard says 
> Copy and paste this code as the first item into the <HEAD> 

Will update

**Comment by summers1981FA** [comment]
Going on the snippet being correct so 👍 from me.

**Pull request merged**
